name: Build and Push Docker Images on Release
on:
  release:
    types: [released]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3

      - name: Set up Just
        uses: extractions/setup-just@v1
        with:
          just-version: "^1.5.0"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME_RYHINO }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_RYHINO }}

      - name: Pass in Git Tag and Invoke `just`
        run: just _gh_actions_parse _ci_push ${{ github.ref }}
